apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          env:
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: azure-secrets, key: DB_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom:
                { secretKeyRef: { name: azure-secrets, key: DB_PASSWORD } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: azure-secrets, key: DB_NAME } }
          ports:
            - containerPort: 5432
