apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: chaniweb-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: azure-secrets, key: DB_USER } }
            - name: DB_PASSWORD
              valueFrom:
                { secretKeyRef: { name: azure-secrets, key: DB_PASSWORD } }
            - name: DB_HOST
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_HOST } }
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: azure-secrets, key: DB_NAME } }
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):5432/$(DB_NAME)"
